spring:
  application:
    name: todo
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testds
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


